version: "3.7"

services:
  app:
    image: "nj-mvc-slack-bot"
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    ports:
      - "3055:3000"
